[package]
name = "uci"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
async-stream = "0.3.6"
pgn-reader = "0.26.0"
shakmaty = "0.27.3"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
